version: "3.8"
services:

  db:
    image: mysql:5.7
    container_name: mysql-container-symfony
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container-symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: